name: Build S22 r0q Kernel (No KernelSU)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ALL dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential ccache flex git \
            libncurses-dev libssl-dev libxml2-utils lz4 lzop \
            python3 python3-pip repo unzip zip zstd \
            clang lld llvm libclang-dev \
            coreutils util-linux sed gawk diffutils procps findutils \
            libseccomp-dev

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 3G

      - name: Build Kernel
        run: |
          ls -la
          chmod +x build_kernel_GKI.sh
          ./build_kernel_GKI.sh

      - name: Upload Kernel Output
        uses: actions/upload-artifact@v4
        with:
          name: S22-Kernel-Output
          path: |
            out/**/*.Image*
            out/**/*.gz-dtb
            out/**/*.ko
